
# --- Временные константы ---
SECONDS_PER_MINUTE = 60
SECONDS_PER_HOUR = 3600
SECONDS_PER_DAY = 86400
MAX_DELAY_DAYS = 380
TICK_INTERVAL_MS = 1000
ALERT_INTERVAL_MS = 1000

# --- Таймауты и интервалы (логика оповещений и удаления) ---
RETRY_DELAY_IMPORTANT_SEC = 60
RETRY_DELAY_IMPORTANT_SOUND_SEC = 15
RETRY_DELAY_NORMAL_SEC = 300
RETRY_DELAY_NORMAL_SOUND_SEC = 60

DELETE_CONFIRM_MAX_SECONDS = 10
DELETE_CONFIRM_MIN_SECONDS = 0.350

# --- Цвета UI (main.py) ---
COLOR_BTN_DEFER_BG = "#888888"
COLOR_BTN_DEFER_FG = "#000000"
COLOR_BTN_DEFER_ACTIVE_BG = "#000000"
COLOR_BTN_DEFER_ACTIVE_FG = "#FFFFFF"

COLOR_BTN_ADD_NORMAL_BG = "#e0ffe0"
COLOR_BTN_ADD_NORMAL_ACTIVE_BG = "#c6e9c6"

COLOR_BTN_ADD_IMPORTANT_BG = "#ffebee"
COLOR_BTN_ADD_IMPORTANT_ACTIVE_BG = "#ffcdd2"

COLOR_BTN_ADD_QUIET_BG = "#888888"
COLOR_BTN_ADD_QUIET_ACTIVE_BG = "#AAAAAA"

COLOR_BTN_MUTE_ACTIVE_BG = "#FF0000"
COLOR_BTN_MUTE_INACTIVE_BG = "#888888"
COLOR_BTN_MUTE_HOVER_BG = "#ffaaaa"


# --- task_block.py ---
COLOR_NORMAL_BG        = "#f0f0f0"
COLOR_NORMAL_ACTIVE    = "#e0e0e0"
COLOR_IMPORTANT_BG     = "#ffebee"
COLOR_IMPORTANT_ACTIVE = "#ffcdd2"
COLOR_FRAME_NORMAL     = "#ffffff"
COLOR_FRAME_IMPORTANT  = "#fff0f0"

COLOR_TEXT_IMPORTANT   = "#b71c1c"

COLOR_BTN_DELETE_NORMAL  = "#f0f0f0"
COLOR_BTN_DELETE_OVERDUE = "#ffcccc"

COLOR_TIME_ALERT_OVERDUE   = "#ffcccc"
COLOR_TIME_ALERT_POSTPONED = "#cceeff"
COLOR_TIME_ALERT_NORMAL    = COLOR_FRAME_NORMAL


# --- Пути ---
TEST_SOUND_PATH = "/usr/share/sounds/freedesktop/stereo/complete.oga"
